apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: us-east1-docker.pkg.dev/maxi-clone/mc-repository-dev/users:latest
          ports:
            - containerPort: 8081
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
  labels:
    app: users
spec:
  type: LoadBalancer
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
