apiVersion: apps/v1
kind: Deployment
metadata:
  name: incidents
  labels:
    app: incidents
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incidents
  template:
    metadata:
      labels:
        app: incidents
    spec:
      containers:
        - name: incidents
          image: us-east1-docker.pkg.dev/maxi-clone/mc-repository-dev/incidents:latest
          ports:
            - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: incidents-svc
  labels:
    app: incidents
spec:
  type: LoadBalancer
  selector:
    app: incidents
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
