spring:
  application:
    name: "incidents-svc"

  datasource:
    url: jdbc:mysql://mysql-service.default.svc.cluster.local:3306/orders
    username: cluster
    password: cluster

  rabbitmq:
    host: rabbitmq-service.default.svc.cluster.local
    port: 5672
    username: guest
    password: guest
    virtual-host: "/"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-svc.default.svc.cluster.local:8761/eureka/
  instance:
    prefer-ip-address: false
    hostname: incidents-svc
    instance-id: ${spring.application.name}:${server.port}

server:
  port: 8086